"""Migración inicial

Revision ID: 0d63361fdb29
Revises: 
Create Date: 2025-12-23 12:22:24.116815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d63361fdb29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rif', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=11), nullable=False),
    sa.Column('rubro', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rif'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=20), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=20), nullable=True),
    sa.Column('primer_apellido', sa.String(length=20), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=20), nullable=True),
    sa.Column('sexo', sa.String(length=3), nullable=True),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('carrera', sa.String(length=100), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('direccion', mysql.LONGTEXT(), nullable=False),
    sa.Column('fecha_de_nacimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('tutores_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=20), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=20), nullable=True),
    sa.Column('primer_apellido', sa.String(length=20), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=20), nullable=True),
    sa.Column('sexo', sa.String(length=3), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('fecha_de_nacimiento', sa.Date(), nullable=True),
    sa.Column('especialidad', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mac_adresss', sa.String(length=25), nullable=False),
    sa.Column('data_session', mysql.LONGTEXT(), nullable=True),
    sa.Column('last_activity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutores_empresariales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('primer_nombre', sa.String(length=20), nullable=False),
    sa.Column('segundo_nombre', sa.String(length=20), nullable=True),
    sa.Column('primer_apellido', sa.String(length=20), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=20), nullable=True),
    sa.Column('sexo', sa.String(length=3), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('fecha_de_nacimiento', sa.Date(), nullable=True),
    sa.Column('cargo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_empresa'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pasantias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('tutor_academico_id', sa.Integer(), nullable=True),
    sa.Column('tutor_empresarial_id', sa.Integer(), nullable=True),
    sa.Column('lapso_academico', sa.String(length=50), nullable=False),
    sa.Column('inicio_pasantias', sa.Date(), nullable=True),
    sa.Column('final_pasantias', sa.Date(), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('trabajo_asignado', mysql.LONGTEXT(), nullable=True),
    sa.Column('titulo_de_informe', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['tutor_academico_id'], ['tutores_academicos.id'], ),
    sa.ForeignKeyConstraint(['tutor_empresarial_id'], ['tutores_empresariales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_adjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasantia_id', sa.Integer(), nullable=False),
    sa.Column('tipo_de_documento', sa.String(length=100), nullable=False),
    sa.Column('ruta', sa.String(length=255), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pasantia_id'], ['pasantias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasantia_id', sa.Integer(), nullable=False),
    sa.Column('nota_tutor_aca', sa.Float(), nullable=True),
    sa.Column('nota_tutor_emp', sa.Float(), nullable=True),
    sa.Column('exposicion', sa.Float(), nullable=True),
    sa.Column('taller_induccion', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pasantia_id'], ['pasantias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluaciones')
    op.drop_table('documentos_adjuntos')
    op.drop_table('pasantias')
    op.drop_table('tutores_empresariales')
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('tutores_academicos')
    op.drop_table('students')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
