"""msg

Revision ID: 15a9cf7bbab3
Revises: 0d63361fdb29
Create Date: 2026-01-05 08:56:59.735695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a9cf7bbab3'
down_revision: Union[str, Sequence[str], None] = '0d63361fdb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutores_academicos', sa.Column('telefono', sa.String(length=11), nullable=False))
    op.create_unique_constraint(None, 'tutores_academicos', ['telefono'])
    op.add_column('tutores_empresariales', sa.Column('telefono', sa.String(length=11), nullable=False))
    op.create_unique_constraint(None, 'tutores_empresariales', ['telefono'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutores_empresariales', type_='unique')
    op.drop_column('tutores_empresariales', 'telefono')
    op.drop_constraint(None, 'tutores_academicos', type_='unique')
    op.drop_column('tutores_academicos', 'telefono')
    # ### end Alembic commands ###
