"""msg

Revision ID: 15bc596fe737
Revises: cef2140ecb45
Create Date: 2026-02-17 10:32:26.835022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '15bc596fe737'
down_revision: Union[str, Sequence[str], None] = 'cef2140ecb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configuraciones', 'valor',
               existing_type=mysql.VARCHAR(length=100),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('configuraciones', 'valor',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
