"""quito null en documentosadjuntos

Revision ID: 67ce40fafa69
Revises: 15a9cf7bbab3
Create Date: 2026-01-07 17:42:28.573087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ce40fafa69'
down_revision: Union[str, Sequence[str], None] = '15a9cf7bbab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
