"""msg

Revision ID: 9e81d1ea6b52
Revises: abb9ef733238
Create Date: 2026-02-07 17:09:13.118609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e81d1ea6b52'
down_revision: Union[str, Sequence[str], None] = 'abb9ef733238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'sexo',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('tutores_academicos', 'sexo',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('tutores_empresariales', 'sexo',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tutores_empresariales', 'sexo',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True)
    op.alter_column('tutores_academicos', 'sexo',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True)
    op.alter_column('students', 'sexo',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True)
    # ### end Alembic commands ###
