"""mensaje

Revision ID: bcd1c1689e9c
Revises: c5912ee5ffa9
Create Date: 2026-01-15 14:52:09.363762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bcd1c1689e9c'
down_revision: Union[str, Sequence[str], None] = 'c5912ee5ffa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sistema_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=True),
    sa.Column('id_registro_afectado', sa.Integer(), nullable=True),
    sa.Column('valores_anteriores', mysql.LONGTEXT(), nullable=True),
    sa.Column('valores_nuevos', mysql.LONGTEXT(), nullable=True),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.Column('ip_maquina', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('enterprises', 'telefono',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.create_unique_constraint(None, 'enterprises', ['telefono'])
    op.add_column('pasantias', sa.Column('plan_de_trabajo', mysql.LONGTEXT(), nullable=True))
    op.add_column('pasantias', sa.Column('sede', sa.Boolean(), nullable=True))
    op.add_column('pasantias', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('pasantias', sa.Column('jefe_de_carta', sa.String(length=255), nullable=True))
    op.add_column('pasantias', sa.Column('cargo_jefe_de_carta', sa.String(length=100), nullable=True))
    op.alter_column('tutores_academicos', 'telefono',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tutores_academicos', 'telefono',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.drop_column('pasantias', 'cargo_jefe_de_carta')
    op.drop_column('pasantias', 'jefe_de_carta')
    op.drop_column('pasantias', 'direccion')
    op.drop_column('pasantias', 'sede')
    op.drop_column('pasantias', 'plan_de_trabajo')
    op.drop_constraint(None, 'enterprises', type_='unique')
    op.alter_column('enterprises', 'telefono',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.drop_table('sistema_logs')
    op.drop_table('configuraciones')
    # ### end Alembic commands ###
