"""cambios

Revision ID: c5912ee5ffa9
Revises: 67ce40fafa69
Create Date: 2026-01-10 12:29:12.519674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c5912ee5ffa9'
down_revision: Union[str, Sequence[str], None] = '67ce40fafa69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enterprises', 'telefono',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('enterprises', 'rubro',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('telefono'), table_name='enterprises')
    op.add_column('pasantias', sa.Column('carrera', sa.String(length=100), nullable=False))
    op.add_column('pasantias', sa.Column('semestre', sa.Integer(), nullable=False))
    op.alter_column('students', 'telefono',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('students', 'direccion',
               existing_type=mysql.LONGTEXT(),
               nullable=True)
    op.drop_index(op.f('telefono'), table_name='students')
    op.drop_column('students', 'semestre')
    op.drop_column('students', 'carrera')
    op.drop_index(op.f('telefono'), table_name='tutores_academicos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('telefono'), 'tutores_academicos', ['telefono'], unique=True)
    op.add_column('students', sa.Column('carrera', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('students', sa.Column('semestre', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_index(op.f('telefono'), 'students', ['telefono'], unique=True)
    op.alter_column('students', 'direccion',
               existing_type=mysql.LONGTEXT(),
               nullable=False)
    op.alter_column('students', 'telefono',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.drop_column('pasantias', 'semestre')
    op.drop_column('pasantias', 'carrera')
    op.create_index(op.f('telefono'), 'enterprises', ['telefono'], unique=True)
    op.alter_column('enterprises', 'rubro',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('enterprises', 'telefono',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
