"""msg

Revision ID: cef2140ecb45
Revises: d98dde33cde9
Create Date: 2026-02-16 14:29:53.403983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef2140ecb45'
down_revision: Union[str, Sequence[str], None] = 'd98dde33cde9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuraciones', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('configuraciones', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('documentos_adjuntos', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('documentos_adjuntos', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('enterprises', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('enterprises', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('evaluaciones', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('evaluaciones', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('pasantias', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('pasantias', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('sistema_logs', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('sistema_logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('students', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tutores_academicos', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tutores_academicos', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('tutores_empresariales', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tutores_empresariales', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('tutores_empresariales', 'updated_at')
    op.drop_column('tutores_empresariales', 'created_at')
    op.drop_column('tutores_academicos', 'updated_at')
    op.drop_column('tutores_academicos', 'created_at')
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'created_at')
    op.drop_column('sistema_logs', 'updated_at')
    op.drop_column('sistema_logs', 'created_at')
    op.drop_column('sessions', 'updated_at')
    op.drop_column('sessions', 'created_at')
    op.drop_column('pasantias', 'updated_at')
    op.drop_column('pasantias', 'created_at')
    op.drop_column('evaluaciones', 'updated_at')
    op.drop_column('evaluaciones', 'created_at')
    op.drop_column('enterprises', 'updated_at')
    op.drop_column('enterprises', 'created_at')
    op.drop_column('documentos_adjuntos', 'updated_at')
    op.drop_column('documentos_adjuntos', 'created_at')
    op.drop_column('configuraciones', 'updated_at')
    op.drop_column('configuraciones', 'created_at')
    # ### end Alembic commands ###
