"""msg

Revision ID: d98dde33cde9
Revises: 9e81d1ea6b52
Create Date: 2026-02-14 09:02:53.511630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd98dde33cde9'
down_revision: Union[str, Sequence[str], None] = '9e81d1ea6b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluaciones', 'taller_induccion',
               existing_type=mysql.FLOAT(),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluaciones', 'taller_induccion',
               existing_type=sa.Boolean(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
