"""msg

Revision ID: e5aadda3a552
Revises: e2d14dad5cbb
Create Date: 2026-01-28 23:17:41.537506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5aadda3a552'
down_revision: Union[str, Sequence[str], None] = 'e2d14dad5cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentos_adjuntos', 'pasantia_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(op.f('documentos_adjuntos_ibfk_1'), 'documentos_adjuntos', type_='foreignkey')
    op.create_foreign_key(None, 'documentos_adjuntos', 'pasantias', ['pasantia_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('evaluaciones_ibfk_1'), 'evaluaciones', type_='foreignkey')
    op.create_foreign_key(None, 'evaluaciones', 'pasantias', ['pasantia_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pasantias_ibfk_4'), 'pasantias', type_='foreignkey')
    op.drop_constraint(op.f('pasantias_ibfk_1'), 'pasantias', type_='foreignkey')
    op.drop_constraint(op.f('pasantias_ibfk_2'), 'pasantias', type_='foreignkey')
    op.drop_constraint(op.f('pasantias_ibfk_3'), 'pasantias', type_='foreignkey')
    op.create_foreign_key(None, 'pasantias', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pasantias', 'tutores_academicos', ['tutor_academico_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pasantias', 'enterprises', ['empresa_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pasantias', 'tutores_empresariales', ['tutor_empresarial_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('sessions_ibfk_1'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tutores_empresariales', 'id_empresa',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(op.f('tutores_empresariales_ibfk_1'), 'tutores_empresariales', type_='foreignkey')
    op.create_foreign_key(None, 'tutores_empresariales', 'enterprises', ['id_empresa'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tutores_empresariales', type_='foreignkey')
    op.create_foreign_key(op.f('tutores_empresariales_ibfk_1'), 'tutores_empresariales', 'enterprises', ['id_empresa'], ['id'])
    op.alter_column('tutores_empresariales', 'id_empresa',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_ibfk_1'), 'sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'pasantias', type_='foreignkey')
    op.drop_constraint(None, 'pasantias', type_='foreignkey')
    op.drop_constraint(None, 'pasantias', type_='foreignkey')
    op.drop_constraint(None, 'pasantias', type_='foreignkey')
    op.create_foreign_key(op.f('pasantias_ibfk_3'), 'pasantias', 'tutores_academicos', ['tutor_academico_id'], ['id'])
    op.create_foreign_key(op.f('pasantias_ibfk_2'), 'pasantias', 'enterprises', ['empresa_id'], ['id'])
    op.create_foreign_key(op.f('pasantias_ibfk_1'), 'pasantias', 'students', ['student_id'], ['id'])
    op.create_foreign_key(op.f('pasantias_ibfk_4'), 'pasantias', 'tutores_empresariales', ['tutor_empresarial_id'], ['id'])
    op.drop_constraint(None, 'evaluaciones', type_='foreignkey')
    op.create_foreign_key(op.f('evaluaciones_ibfk_1'), 'evaluaciones', 'pasantias', ['pasantia_id'], ['id'])
    op.drop_constraint(None, 'documentos_adjuntos', type_='foreignkey')
    op.create_foreign_key(op.f('documentos_adjuntos_ibfk_1'), 'documentos_adjuntos', 'pasantias', ['pasantia_id'], ['id'])
    op.alter_column('documentos_adjuntos', 'pasantia_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
